@startuml
skinparam groupInheritance 2

class "Character" as Character {
  -name: string
  -health: int
  +getName()
  +getHealth()
  +attack()
}

class "Enemy" as Enemy {
  -damage: int
  +getDamage()
}

class "Attack" as Attack {
  -name: string
  -damage: int
  +getName()
  +getDamage()
}

class "Player" as Player {
  +attacks: Attack[]
  +inventory: Item[]
  +useItem()
}


enum "ItemType" as ItemType {
  Food
  Weapon
}

class "Item" as Item {
  +type: ItemType
  +use()
}

class "Room" as Room {
  .. Neighboring rooms ..
  +north: Room?
  +south: Room?
  +east: Room?
  +west: Room?
  .. Props ..
  +enemies: Enemy[]
  +items: Item[]
}

ItemType --> Item::type
Item --> Room::items

Enemy --> Room::enemies

Attack --> Player::attacks
Player::inventory <-- Item

Character <|-- Player
Character <|-- Enemy

@enduml
